version: '3.8'

services:
  infrastructure-api:
    build:
      context: ./Infrastructure/services/api
      dockerfile: Dockerfile
    container_name: metabundle-infrastructure-api
    ports:
      - "${API_PORT:-9090}:${API_PORT:-9090}"
    environment:
      - METABUNDLE_TEST_MODE=${METABUNDLE_TEST_MODE:-true}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_ORG=${GITHUB_ORG:-MetaBundle}
      - REPO_BASE_DIR=${REPO_BASE_DIR:-/repos}
      - API_PORT=${API_PORT:-9090}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-9091}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - PYTHONPATH=/app:/app/services
      - VIRTUAL_HOST=${API_DOMAIN:-api.metabundle.yourdomain.com}
      - LETSENCRYPT_HOST=${API_DOMAIN:-api.metabundle.yourdomain.com}
    volumes:
      - ./Infrastructure/services:/app/services
      - ./Infrastructure/services/api/src:/app/src
    networks:
      - metabundle-network
    restart: unless-stopped

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    container_name: metabundle-dashboard
    ports:
      - "5001:${FLASK_RUN_PORT:-5000}"
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - SECRET_KEY=${SECRET_KEY:-dev_key_replace_in_production}
      - INFRASTRUCTURE_API_URL=${INFRASTRUCTURE_API_URL:-http://infrastructure-api:${API_PORT:-9090}}
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5000}
      - VIRTUAL_HOST=${DASHBOARD_DOMAIN:-dashboard.metabundle.yourdomain.com}
      - LETSENCRYPT_HOST=${DASHBOARD_DOMAIN:-dashboard.metabundle.yourdomain.com}
    depends_on:
      - infrastructure-api
    volumes:
      - ./Dashboard/src:/app/src
    networks:
      - metabundle-network
    restart: unless-stopped

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/dhparam:/etc/nginx/dhparam
    networks:
      - metabundle-network
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - metabundle-network
    restart: unless-stopped

networks:
  metabundle-network:
    driver: bridge
